version: 0.2 

#env:
  #parameter-store:
   # DOCKERHUB_USER: "/docker/username"
    #DOCKERHUB_TOKEN: "/docker/token"  

phases:
  pre_build:
    commands:
      #- echo ${DOCKERHUB_TOKEN}  |  docker login -u ${DOCKERHUB_USER} --password-stdin
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 767397858010.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      #- docker build -t my-angular-app:latest .
      - docker build -t angular-docker-53 .
  post_build:
    commands:
      #- docker tag my-angular-app:latest ${DOCKERHUB_USER}/angular-docker-repo-b10:env
      #- docker push ${DOCKERHUB_USER}/angular-docker-repo-b10:env

      - docker tag angular-docker-53:latest 767397858010.dkr.ecr.ap-south-1.amazonaws.com/angular-docker-53:${CODEBUILD_BUILD_NUMBER}
      - docker push 767397858010.dkr.ecr.ap-south-1.amazonaws.com/angular-docker-53:${CODEBUILD_BUILD_NUMBER}

      - printf '[{"name":"angularimage53","imageuri":"%s"}]' 767397858010.dkr.ecr.ap-south-1.amazonaws.com/angular-docker-53:${CODEBUILD_BUILD_NUMBER} > taskDefination.json
Artifact:
  files:
    - taskDefination.json